added some basic error handling

diff --git a/cvescan b/cvescan
--- a/cvescan
+++ b/cvescan
@@ -1,9 +1,9 @@
 #!/bin/bash
 
-if ! lsb_release -a 2>&1 | grep -q -E '^Distributor ID:\s+Ubuntu$' ; then
-	echo "Not Ubuntu, not running" >&2
+error() {
+	echo "Error: $@" >&2
 	exit 4
-fi
+}
 
 usage() {
 	cat <<-EOF
@@ -36,6 +36,10 @@ usage() {
 	EOF
 	exit 3
 }
+
+if ! lsb_release -a 2>&1 | grep -q -E '^Distributor ID:\s+Ubuntu$' ; then
+	error "Not Ubuntu, not running"
+fi
 
 RELEASE=$(lsb_release -c -s)
 OVAL_FILE=com.ubuntu.${RELEASE}.cve.oval.xml
@@ -99,19 +103,28 @@ $REMOVE && rm -f $OVAL_FILE $OVAL_ZIP $REPORT $RESULTS $LOG
 
 if [[ ! -f $OVAL_FILE || $(($NOW - $(stat -c %Y $OVAL_FILE))) -gt $EXPIRE ]] ; then
 	$VERBOSE && echo "Downloading ${OVAL_BASE_URL}/${OVAL_ZIP}"
-	wget -q ${OVAL_BASE_URL}/${OVAL_ZIP}
-	$VERBOSE && echo "Unzipping ${OVAL_ZIP}"
-	bunzip2 -f $OVAL_ZIP
+	if wget -q ${OVAL_BASE_URL}/${OVAL_ZIP} ; then
+		$VERBOSE && echo "Unzipping ${OVAL_ZIP}"
+		if ! bunzip2 -f $OVAL_ZIP ; then
+			error "Failed to unzip $OVAL_ZIP"
+		fi
+	else
+		error "Failed to wget ${OVAL_BASE_URL}/${OVAL_ZIP}"
+	fi
 fi
 
 if [[ ! -f $RESULTS || $(($NOW - $(stat -c %Y $RESULTS))) -gt $EXPIRE ]] ; then
 	$VERBOSE && echo "Running oval scan (output logged to $LOG)"
-	oscap oval eval --results $RESULTS $OVAL_FILE >$LOG >&1
+	if ! oscap oval eval --results $RESULTS $OVAL_FILE >$LOG >&1 ; then
+		error "Failed to run oval scan"
+	fi
 fi
 
 if [[ ! -f $REPORT ||$(($NOW - $(stat -c %Y $REPORT))) -gt $EXPIRE  ]] ; then
 	$VERBOSE && echo "Generating oval report from scan results (output logged to $LOG)"
-	oscap oval generate report --output $REPORT $RESULTS >>$LOG >&1
+	if ! oscap oval generate report --output $REPORT $RESULTS >>$LOG >&1 ; then
+		error "Failed to generate oval report"
+	fi
 fi
 
 $VERBOSE && echo "Running xsltproc to generate CVE list - fixable/unfixable and filtered by priority"
