add manifest option, fix output redirection bug

diff --git a/cvescan b/cvescan
--- a/cvescan
+++ b/cvescan
@@ -23,6 +23,12 @@ usage() {
 		         -s enable script/silent mode
 		            To be used with -c CVE-1984-54321, do not print text output
 		            exit 0 if not vulnerable, exit 1 if vulnerable
+		         -m <xenial|bionic|disco|eoan>
+		            Enable manifest mode
+		            Do not scan localhost. Instead run a scan against a Ubuntu Official Cloud 
+		            Image package manifest file.
+                            The script will use a server manifest file.
+		            This enables the -r option.
 		         -n enable nagios mode
 		            Typical nagios-style "OK|WARNING|CRITICAL|UNKNOWN" messages with 0-3 exit codes
 		            0/OK = not vulnerable to any CVEs
@@ -52,12 +58,14 @@ VERBOSE=false
 REMOVE=false
 SILENT=false
 NAGIOS=false
+MANIFEST=false
+MANIFEST_FILE=manifest
 ALL=false
 PRIORITY=medium
 NOW=$(date +%s)
 EXPIRE=86400
 
-while getopts ":ac:p:rsnv" op ; do
+while getopts ":ac:p:rsnm:v" op ; do
 	case "${op}" in
 		a)
 			ALL=true
@@ -82,6 +90,18 @@ while getopts ":ac:p:rsnv" op ; do
 		s)
 			SILENT=true
 			;;
+		m)
+			MANIFEST=true
+			REMOVE=true
+			if [[ ${OPTARG} =~ ^(xenial|bionic|disco|eoan)$ ]] ; then
+				RELEASE=${OPTARG}
+				OVAL_FILE=oci.com.ubuntu.${RELEASE}.cve.oval.xml
+				OVAL_ZIP=${OVAL_FILE}.bz2
+				MANIFEST_URL="https://cloud-images.ubuntu.com/${RELEASE}/current/${RELEASE}-server-cloudimg-amd64.manifest"
+			else
+				usage
+			fi
+			;;
 		n)
 			NAGIOS=true
 			;;
@@ -95,11 +115,15 @@ while getopts ":ac:p:rsnv" op ; do
 done
 shift $((OPTIND-1))
 
-$VERBOSE && $REMOVE && echo "Removing files: $OVAL_FILE $OVAL_ZIP $REPORT $RESULTS $LOG"
 $VERBOSE && $ALL && echo "Reporting on ALL CVEs, not just those that can be fixed by updates"
 $VERBOSE && $NAGIOS && echo "Running in Nagios Mode"
 $VERBOSE && echo "Priority filter is \"$PRIORITY\""
-$REMOVE && rm -f "$OVAL_FILE" "$OVAL_ZIP" "$REPORT" "$RESULTS" "$LOG"
+if [[ -f "$MANIFEST_FILE" && ! $($REMOVE) && ! $($MANIFEST) ]] ; then
+	$VERBOSE && echo "$MANIFEST_FILE found when not in manifest mode, enabling -r option"
+	REMOVE=true
+fi
+$VERBOSE && $REMOVE && echo "Removing files: $OVAL_FILE $OVAL_ZIP $REPORT $RESULTS $LOG $MANIFEST_FILE"
+$REMOVE && rm -f "$OVAL_FILE" "$OVAL_ZIP" "$REPORT" "$RESULTS" "$LOG" "$MANIFEST_FILE"
 
 if [[ ! -f $OVAL_FILE || $((NOW - $(stat -c %Y "$OVAL_FILE"))) -gt $EXPIRE ]] ; then
 	$VERBOSE && echo "Downloading ${OVAL_BASE_URL}/${OVAL_ZIP}"
@@ -113,16 +137,25 @@ if [[ ! -f $OVAL_FILE || $((NOW - $(stat -c %Y "$OVAL_FILE"))) -gt $EXPIRE ]] ; 
 	fi
 fi
 
+if $MANIFEST ; then
+	if [[ ! -f $MANIFEST_FILE || $((NOW - $(stat -c %Y "$MANIFEST_FILE"))) -gt $EXPIRE ]] ; then
+		$VERBOSE && echo "Downloading ${MANIFEST_URL}"
+		if ! wget -q -O "${MANIFEST_FILE}" "${MANIFEST_URL}" ; then
+			error "Failed to wget ${MANIFEST_FILE} from ${MANIFEST_URL}"
+		fi
+	fi
+fi
+
 if [[ ! -f $RESULTS || $((NOW - $(stat -c %Y "$RESULTS"))) -gt $EXPIRE ]] ; then
-	$VERBOSE && echo "Running oval scan (output logged to $LOG)"
-	if ! oscap oval eval --results "$RESULTS" "$OVAL_FILE" >$LOG >&1 ; then
+	$VERBOSE && echo "Running oval scan oscap oval eval --results $RESULTS $OVAL_FILE (output logged to $LOG)"
+	if ! oscap oval eval --results "$RESULTS" "$OVAL_FILE" >$LOG 2>&1 ; then
 		error "Failed to run oval scan"
 	fi
 fi
 
 if [[ ! -f $REPORT ||$((NOW - $(stat -c %Y "$REPORT"))) -gt $EXPIRE  ]] ; then
 	$VERBOSE && echo "Generating oval report from scan results (output logged to $LOG)"
-	if ! oscap oval generate report --output $REPORT $RESULTS >>$LOG >&1 ; then
+	if ! oscap oval generate report --output $REPORT $RESULTS >>$LOG 2>&1 ; then
 		error "Failed to generate oval report"
 	fi
 fi
