add test mode for testing of basic oscap and xslt functionaility

diff --git a/snapcraft/bin/cvescan b/snapcraft/bin/cvescan
--- a/snapcraft/bin/cvescan
+++ b/snapcraft/bin/cvescan
@@ -39,6 +39,9 @@ usage() {
 		            3/UNKNOWN = something went wrong with the script, or the oscap oval scan
 		         -r remove zip, oval, xml, and htm files to force redownload/regeneration
 		            Default is to use them if they already exist and are less than 1 day old
+		         -t Test mode, use test OVAL data to validate that cvescan and oscap are working as expected
+		            In test mode files are not downloaded
+		            In test mode the remove and verbose options are enabled automatically
 		         -v enable verbose messages
 	EOF
 	exit 3
@@ -80,8 +83,10 @@ SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 XSLT_FILE=${SCRIPTDIR}/text.xsl
 VERBOSE_OSCAP_OPTIONS=""
 CURL_OPTIONS="--fail --silent --show-error"
+TESTMODE=false
+TESTCANARYFILE=cvescan.test
 
-while getopts ":ac:p:rsnm:v" op ; do
+while getopts ":ac:p:rsnm:tv" op ; do
 	case "${op}" in
 		a)
 			ALL=true
@@ -120,10 +125,11 @@ while getopts ":ac:p:rsnm:v" op ; do
 		n)
 			NAGIOS=true
 			;;
+		t)
+			TESTMODE=true
+			;;
 		v)
 			VERBOSE=true
-			VERBOSE_OSCAP_OPTIONS="--verbose WARNING --verbose-log-file debug.log"
-			CURL_OPTIONS="--fail"
 			;;
 		*)
 			usage
@@ -131,6 +137,7 @@ while getopts ":ac:p:rsnm:v" op ; do
 	esac
 done
 shift $((OPTIND-1))
+
 
 if [[ -n "$SNAP_USER_COMMON" ]] ; then
 	$VERBOSE && echo "Running as a snap, changing to '$SNAP_USER_COMMON' directory"
@@ -143,11 +150,31 @@ fi
 
 [[ -f "$XSLT_FILE" ]] || error "Missing text.xsl file at '$XSLT_FILE', this file should have installed with cvescan"
 
+if $TESTMODE ; then
+	VERBOSE=true
+	MANIFEST=false
+	REMOVE=true
+	PRIORITY=all
+	OVAL_FILE=${SCRIPTDIR}/com.ubuntu.test.cve.oval.xml
+	[[ -f "$OVAL_FILE" ]] || error "Missing test OVAL file at '$OVAL_FILE', this file should have installed with cvescan"
+elif [[ -f "$TESTCANARYFILE" ]] ; then
+	$VERBOSE && "Detected previous run in test mode, cleaning up"
+	$VERBOSE && "Removing file: '$TESTCANARYFILE'"
+	rm "$TESTCANARYFILE"
+	REMOVE=true
+fi
+
+if $VERBOSE ; then
+	VERBOSE_OSCAP_OPTIONS="--verbose WARNING --verbose-log-file debug.log"
+	CURL_OPTIONS="--fail"
+fi
+
 if [[ -n "$CVE" ]] ; then
 	ALL=true
 	PRIORITY=all
 fi
 
+$VERBOSE && $TESTMODE && echo "Running in TEST MODE"
 $VERBOSE && $ALL && echo "Reporting on ALL CVEs, not just those that can be fixed by updates"
 $VERBOSE && $NAGIOS && echo "Running in Nagios Mode"
 $VERBOSE && echo "Priority filter is '$PRIORITY'"
@@ -155,10 +182,14 @@ if $MANIFEST ; then
 	$VERBOSE && echo "Removing cached manifest, report and results files"
 	rm -f "$MANIFEST_FILE" "$REPORT" "$RESULTS"
 fi
-$VERBOSE && $REMOVE && echo "Removing files: $OVAL_FILE $OVAL_ZIP $REPORT $RESULTS $LOG $MANIFEST_FILE" 
-$REMOVE && rm -f "$OVAL_FILE" "$OVAL_ZIP" "$REPORT" "$RESULTS" "$LOG" "$MANIFEST_FILE" 
 
-if [[ ! -f $OVAL_FILE || $((NOW - $(stat -c %Y "$OVAL_FILE"))) -gt $EXPIRE ]] ; then
+$VERBOSE && $REMOVE && echo "Removing files: $OVAL_ZIP $REPORT $RESULTS $LOG $MANIFEST_FILE" 
+$REMOVE && rm -f "$OVAL_ZIP" "$REPORT" "$RESULTS" "$LOG" "$MANIFEST_FILE" 
+
+$VERBOSE && $TESTMODE && echo "Removing file: $OVAL_FILE"
+$REMOVE && ! $TESTMODE && rm -f "$OVAL_FILE"
+
+if ! $TESTMODE && [[ ! -f $OVAL_FILE || $((NOW - $(stat -c %Y "$OVAL_FILE"))) -gt $EXPIRE ]] ; then
 	$VERBOSE && echo "Downloading ${OVAL_BASE_URL}/${OVAL_ZIP}"
 	if curl ${CURL_OPTIONS} "${OVAL_BASE_URL}/${OVAL_ZIP}" -o "${OVAL_ZIP}"; then
 		$VERBOSE && echo "Unzipping ${OVAL_ZIP}"
@@ -186,6 +217,7 @@ if [[ ! -f $RESULTS || $((NOW - $(stat -c %Y "$RESULTS"))) -gt $EXPIRE ]] ; then
 	fi
 fi
 
+# TODO: why is snap_user_common checked here? remove the check?
 if [[ -n "$SNAP_USER_COMMON" && ( ! -f $REPORT || $((NOW - $(stat -c %Y "$REPORT"))) -gt $EXPIRE ) ]] ; then
 	$VERBOSE && echo "Generating oval report from scan results (output logged to ${PWD}/${LOG})"
 	if ! oscap oval generate report --output $REPORT $RESULTS >>$LOG 2>&1 ; then
@@ -201,6 +233,7 @@ else
 	CVE_COUNT_ALL_FILTERED=$(wc -l <<<"$CVE_LIST_ALL_FILTERED")
 fi
 $VERBOSE && echo "$CVE_COUNT_ALL_FILTERED vulnerabilities found with priority of $PRIORITY or higher:"
+$VERBOSE && echo "$CVE_LIST_ALL_FILTERED"
 
 $VERBOSE && echo "Running xsltproc to generate CVE list - fixable and filtered by priority"
 CVE_LIST_FIXABLE_FILTERED=$(xsltproc --stringparam showAll false --stringparam priority "$PRIORITY" "$XSLT_FILE" "$RESULTS" | sed /^$/d)
@@ -210,8 +243,30 @@ else
 	CVE_COUNT_FIXABLE_FILTERED=$(wc -l <<<"$CVE_LIST_FIXABLE_FILTERED")
 fi
 $VERBOSE && echo "$CVE_COUNT_FIXABLE_FILTERED CVEs found with priority of $PRIORITY or higher that can be fixed with package updates:"
+$VERBOSE && echo "$CVE_LIST_FIXABLE_FILTERED"
 
 $VERBOSE && [[ -n "$SNAP_USER_COMMON" ]] && echo "Full HTML report available in ${PWD}/${REPORT}"
+
+if $TESTMODE ; then
+	touch "$TESTCANARYFILE"
+	if [[ 		$CVE_COUNT_ALL_FILTERED -eq 2 &&
+			$CVE_LIST_ALL_FILTERED =~ CVE-1970-0300 &&
+			$CVE_LIST_ALL_FILTERED =~ CVE-1970-0400 &&
+			! $CVE_LIST_ALL_FILTERED =~ CVE-1970-0200 &&
+			! $CVE_LIST_ALL_FILTERED =~ CVE-1970-0500 ]] ; then
+		echo "first test passed"
+	else
+		error "first test failed"
+	fi
+
+	if [[ $CVE_COUNT_FIXABLE_FILTERED -eq 1 && $CVE_LIST_FIXABLE_FILTERED =~ ^CVE-1970-0400$ ]] ; then
+		echo "second test passed"
+	else
+		error "second test failed"
+	fi
+fi
+
+$VERBOSE && echo "Normal non-verbose output will appear below"
 $VERBOSE && echo
 
 if $NAGIOS  ; then
@@ -223,7 +278,7 @@ if $NAGIOS  ; then
 		echo "$CVE_LIST_FIXABLE_FILTERED"
 		exit 2
 	elif [ -n "$CVE_LIST_ALL_FILTERED" ] ; then
-		echo "WARNING: $CVE_COUNT_ALL_FILTERED CVEs that can be fixed with package updates"
+		echo "WARNING: $CVE_COUNT_ALL_FILTERED CVEs with priority $PRIORITY or higher"
 		echo "$CVE_LIST_ALL_FILTERED"
 		exit 1
 	else
