Allow test mode regardless of release/series Issue #4 - Compare timestamp of results.xml to /var/log/dpkg.log and re-run oscap if packages have changed since it was generated. Previously this was only deleted if it was more than 24 hours old.

diff --git a/snapcraft/bin/cvescan b/snapcraft/bin/cvescan
--- a/snapcraft/bin/cvescan
+++ b/snapcraft/bin/cvescan
@@ -58,10 +58,6 @@ if [[ ! $DISTRIB_ID =~ ^Ubuntu$ ]] ; then
 	error "DISTRIB_ID=${DISTRIB_ID} in /etc/lsb-release is not Ubuntu, not running"
 fi
 
-if [[ ! $DISTRIB_CODENAME =~ trusty|xenial|bionic|eoan ]] ; then
-	error "DISTRIB_CODENAME=${DISTRIB_CODENAME} in /etc/lsb-release is not trusty|xenial|bionic|eoan, not running"
-fi
-
 RELEASE=$DISTRIB_CODENAME
 OVAL_FILE=com.ubuntu.${RELEASE}.cve.oval.xml
 OVAL_ZIP=${OVAL_FILE}.bz2
@@ -139,16 +135,30 @@ done
 shift $((OPTIND-1))
 
 
+if ! $TESTMODE && [[ ! $DISTRIB_CODENAME =~ trusty|xenial|bionic|eoan ]] ; then
+	error "DISTRIB_CODENAME=${DISTRIB_CODENAME} in /etc/lsb-release is not trusty|xenial|bionic|eoan, not running"
+fi
+
 if [[ -n "$SNAP_USER_COMMON" ]] ; then
 	$VERBOSE && echo "Running as a snap, changing to '$SNAP_USER_COMMON' directory"
 	$VERBOSE && echo "Downloaded files, log files and temporary reports will be in '$SNAP_USER_COMMON'"
 	cd $SNAP_USER_COMMON
 else
-        [[ -x $(which oscap) ]]    || error "Missing oscap command. Run 'sudo apt install libopenscap8'"
-        [[ -x $(which xsltproc) ]] || error "Missing xsltproc command. Run 'sudo apt install xsltproc'"
+        [[ -x $(which oscap) ]]    || error "Missing oscap command. Run 'sudo apt install libopenscap8 xsltproc curl'"
+        [[ -x $(which xsltproc) ]] || error "Missing xsltproc command. Run 'sudo apt install libopenscap8 xsltproc curl'"
+        [[ -x $(which curl) ]]     || error "Missing curl command. Run 'sudo apt install libopenscap8 xsltproc curl'"
 fi
 
 [[ -f "$XSLT_FILE" ]] || error "Missing text.xsl file at '$XSLT_FILE', this file should have installed with cvescan"
+
+if [[ -f /var/log/dpkg.log && -f $RESULTS ]] ; then 
+	PACKAGE_CHANGE_TS=$(stat -c %Y /var/log/dpkg.log)
+	RESULTS_TS=$(stat -c %Y $RESULTS)
+	if [[ $PACKAGE_CHANGE_TS -gt $RESULTS_TS ]] ; then
+		$VERBOSE && echo "Removing $RESULTS file because it is older than /var/log/dpkg.log"
+		rm $RESULTS
+	fi
+fi
 
 if $TESTMODE ; then
 	VERBOSE=true
@@ -158,8 +168,8 @@ if $TESTMODE ; then
 	OVAL_FILE=${SCRIPTDIR}/com.ubuntu.test.cve.oval.xml
 	[[ -f "$OVAL_FILE" ]] || error "Missing test OVAL file at '$OVAL_FILE', this file should have installed with cvescan"
 elif [[ -f "$TESTCANARYFILE" ]] ; then
-	$VERBOSE && "Detected previous run in test mode, cleaning up"
-	$VERBOSE && "Removing file: '$TESTCANARYFILE'"
+	$VERBOSE && echo "Detected previous run in test mode, cleaning up"
+	$VERBOSE && echo "Removing file: '$TESTCANARYFILE'"
 	rm "$TESTCANARYFILE"
 	REMOVE=true
 fi
