minor changes to address some feedback

diff --git a/snapcraft/bin/cvescan b/snapcraft/bin/cvescan
--- a/snapcraft/bin/cvescan
+++ b/snapcraft/bin/cvescan
@@ -128,13 +128,14 @@ shift $((OPTIND-1))
 
 if [[ -n "$SNAP_USER_COMMON" ]] ; then
 	$VERBOSE && echo "Running as a snap, changing to '$SNAP_USER_COMMON' directory"
+	$VERBOSE && echo "Downloaded files, log files and temporary reports will be in '$SNAP_USER_COMMON'"
 	cd $SNAP_USER_COMMON
 else
-        [[ -x $(which oscap) ]]     || error "Missing oscap command. Run 'sudo apt install libopenscap8'"
+        [[ -x $(which oscap) ]]    || error "Missing oscap command. Run 'sudo apt install libopenscap8'"
         [[ -x $(which xsltproc) ]] || error "Missing xsltproc command. Run 'sudo apt install xsltproc'"
 fi
 
-[[ -f "$XSLT_FILE" ]] || error "Missing text.xsl file at '$XSLT_FILE'"
+[[ -f "$XSLT_FILE" ]] || error "Missing text.xsl file at '$XSLT_FILE', this file should have installed with cvescan"
 
 if [[ -n "$CVE" ]] ; then
 	ALL=true
@@ -159,7 +160,7 @@ if [[ ! -f $OVAL_FILE || $((NOW - $(stat -c %Y "$OVAL_FILE"))) -gt $EXPIRE ]] ; 
 			error "Failed to unzip $OVAL_ZIP"
 		fi
 	else
-		error "Failed to curl ${OVAL_BASE_URL}/${OVAL_ZIP}"
+		error "Failed to curl, '${OVAL_BASE_URL}/${OVAL_ZIP}' Is this a currently supported Ubuntu version?"
 	fi
 fi
 
@@ -173,14 +174,14 @@ if $MANIFEST ; then
 fi
 
 if [[ ! -f $RESULTS || $((NOW - $(stat -c %Y "$RESULTS"))) -gt $EXPIRE ]] ; then
-	$VERBOSE && echo "Running oval scan oscap oval eval $VERBOSE_OSCAP_OPTIONS --results $RESULTS $OVAL_FILE (output logged to $LOG)"
+	$VERBOSE && echo "Running oval scan oscap oval eval $VERBOSE_OSCAP_OPTIONS --results $RESULTS $OVAL_FILE (output logged to ${CWD}/${LOG})"
 	if ! oscap oval eval $VERBOSE_OSCAP_OPTIONS --results "$RESULTS" "$OVAL_FILE" >$LOG 2>&1 ; then
 		error "Failed to run oval scan"
 	fi
 fi
 
 if [[ -n "$SNAP_USER_COMMON" && ( ! -f $REPORT || $((NOW - $(stat -c %Y "$REPORT"))) -gt $EXPIRE ) ]] ; then
-	$VERBOSE && echo "Generating oval report from scan results (output logged to $LOG)"
+	$VERBOSE && echo "Generating oval report from scan results (output logged to ${CWD}/${LOG})"
 	if ! oscap oval generate report --output $REPORT $RESULTS >>$LOG 2>&1 ; then
 		error "Failed to generate oval report"
 	fi
@@ -204,7 +205,7 @@ else
 fi
 $VERBOSE && echo "$CVE_COUNT_FIXABLE_FILTERED CVEs found with priority of $PRIORITY or higher that can be fixed with package updates:"
 
-$VERBOSE && [[ -n "$SNAP_USER_COMMON" ]] && echo "Full HTML report availble in $REPORT"
+$VERBOSE && [[ -n "$SNAP_USER_COMMON" ]] && echo "Full HTML report availble in ${CWD}/${REPORT}"
 $VERBOSE && echo
 
 if $NAGIOS  ; then
